version: '3.6'

services:
  local-mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: testtest
      MYSQL_DATABASE: test
      MYSQL_USER: tester
      MYSQL_PASSWORD: testtest
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
